import { create } from "zustand";
import type { AlertItem, Train } from "@/types";

const MAX_ALERTS = 30;

interface NetworkStoreState {
  trains: Train[];
  alerts: AlertItem[];
  isLiveMode: boolean;
  selectedTrainId: string | null;

  setTrains: (trains: Train[]) => void;
  setAlerts: (alerts: AlertItem[]) => void;
  /** Adds newly-generated alerts (see alertService.evaluate) to the front of the list, capped so a long-running demo session doesn't grow this unboundedly. */
  prependAlerts: (alerts: AlertItem[]) => void;
  selectTrain: (trainId: string | null) => void;
  toggleLiveMode: () => void;
  markAlertRead: (alertId: string) => void;
  markAllAlertsRead: () => void;
}

/**
 * Holds cross-page network state (live trains, alerts) so pages like
 * Dashboard, Live Network, and Alerts stay in sync without prop drilling.
 * Populated via the service layer (see hooks/useTrains, hooks/useAlerts)
 * for the initial static seed, and via store/useSimulationStore.ts's tick
 * loop (through alertService.evaluate) for alerts genuinely generated by
 * the live demo train's state changing — this store never fetches or
 * evaluates anything itself.
 */
export const useNetworkStore = create<NetworkStoreState>((set) => ({
  trains: [],
  alerts: [],
  isLiveMode: true,
  selectedTrainId: null,

  setTrains: (trains) => set({ trains }),
  setAlerts: (alerts) => set({ alerts }),
  prependAlerts: (newAlerts) =>
    set((state) => ({
      alerts: newAlerts.length ? [...newAlerts, ...state.alerts].slice(0, MAX_ALERTS) : state.alerts,
    })),
  selectTrain: (trainId) => set({ selectedTrainId: trainId }),
  toggleLiveMode: () => set((state) => ({ isLiveMode: !state.isLiveMode })),
  markAlertRead: (alertId) =>
    set((state) => ({
      alerts: state.alerts.map((alert) =>
        alert.id === alertId ? { ...alert, read: true } : alert,
      ),
    })),
  markAllAlertsRead: () =>
    set((state) => ({
      alerts: state.alerts.map((alert) => ({ ...alert, read: true })),
    })),
}));
